services:
  camera-app:
    build: .
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer
    volumes:
      - ./app:/code/app
      - ./config.json:/code/config.json
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  config-web:
    build: ./web
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/code/config.json
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
